# Generated by Django 5.2.4 on 2025-10-31 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_chapterlikelog_chapterviewlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterviewlog',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='book',
            name='favorites',
        ),
        migrations.DeleteModel(
            name='ChapterLikeLog',
        ),
        migrations.DeleteModel(
            name='ChapterViewLog',
        ),
    ]
