# Generated by Django 5.2.4 on 2025-11-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_date_of_birth_user_gender_alter_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreed_to_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_version',
            field=models.CharField(default='1.0', max_length=10),
        ),
    ]
